#!/bin/bash
makeuser=./makeuser.sh
groupadd Doctor
groupadd Patient
groupadd Manager
groupadd Health_Care_Provider
groupadd Administrator

$makeuser gloria Gloria Manager
$makeuser linda Linda Health_Care_Provider
$makeuser ian Ian Health_Care_Provider
$makeuser mary Mary Doctor
$makeuser markus Markus Doctor
$makeuser margaret Margaret Patient
$makeuser george George Patient
$makeuser russell Russell Patient
$makeuser patricia Patricia Patient
$makeuser amangle Mangle Administrator
